services:
  # PHP + Laravel
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stl-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - stl-network

  # Веб-сервер
  webserver:
    image: nginx:alpine
    container_name: stl-webserver
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - stl-network

  # База данных
  db:
    image: mysql:8.0
    container_name: stl-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-slot_booking}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-laravel}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - stl-network

  # Redis для кеширования
  redis:
    image: redis:alpine
    container_name: stl-redis
    ports:
      - "6379:6379"
    networks:
      - stl-network

networks:
  stl-network:
    driver: bridge

volumes:
  dbdata:
    driver: local